services:
    hana-app-pdf:
        image: nicklas373/hana-app-pdf-sit:1.4
        container_name: "hana-app-pdf"
        cpus: 2.0
        mem_limit: 512M
        mem_reservation: 256M
        restart: unless-stopped
        working_dir: /var/www/html/hanaci-pdf
        environment:
            - APP_NAME=pdf.hana-ci.com
        volumes:
            - hana-app-pdf:/var/www/html/hanaci-pdf
        networks:
            - hana-network
        depends_on:
            - hana-api-services
            - hana-instance-services
    hana-api-services:
        image: nicklas373/hana-api-services-sit:1.6
        container_name: "hana-api-services"
        cpus: 2.0
        mem_limit: 512M
        mem_reservation: 256M
        restart: always
        working_dir: /var/www/html/hanaci-api
        environment:
            - APP_NAME=gw.hana-ci.com
        volumes:
            - hana-api-services:/var/www/html/hanaci-api
        networks:
            - hana-network
        depends_on:
            - hana-db-services
            - hana-instance-services
    hana-db-services:
        image: postgres:16.1
        container_name: "hana-db-services"
        restart: unless-stopped
        cpus: 1.0
        mem_limit: 256M
        mem_reservation: 128M
        ports:
            - "${DB_PORT:-5432}:5432"
        env_file:
            - .env
        environment:
            PGPASSWORD: "${DB_PASSWORD}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD}"
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - "hana-db-services:/var/lib/postgresql/data"
            - "./module/instance/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh"
        networks:
            - hana-network
        depends_on:
            - hana-instance-services
    hana-instance-services:
        image: nicklas373/hana-instance-services-sit:1.3
        container_name: "hana-instance-services"
        cpus: 2.0
        mem_limit: 1G
        mem_reservation: 512M
        restart: always
        ports:
            - "80:80"
            - "81:81"
        volumes:
            - ./module/imagick/policy.xml:/etc/ImageMagick-6/policy.xml
            - ./module/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./module/nginx/sites-available/api-hanaci.conf:/etc/nginx/sites-available/api-hanaci.conf
            - ./module/nginx/sites-available/pdf-hanaci.conf:/etc/nginx/sites-available/pdf-hanaci.conf
            - ./module/php/php.ini:/etc/php/8.2/cli/conf.d/99-hana.ini
            - ./module/php/php.ini:/etc/php/8.2/fpm/conf.d/99-hana.ini
            - hana-app-pdf:/var/www/html/hanaci-pdf
            - hana-api-services:/var/www/html/hanaci-api
            - hana-instance-services:/var/log/supervisor
        networks:
            - hana-network
networks:
    hana-network:
        driver: bridge
volumes:
    hana-db-services:
        driver: local
    hana-app-pdf:
        driver: local
    hana-api-services:
        driver: local
    hana-instance-services:
        driver: local
