version: '3.8'
services:
    hana-container-app-pdf:
        image: nicklas373/hana-container-app-pdf-sit:1.3
        container_name: app-pdf-container
        cpus: 1.0
        mem_limit: 256m
        mem_reservation: 128M
        restart: unless-stopped
        working_dir: /var/www/html/hanaci-pdf
        environment:
            - APP_NAME=sit.pdf.hana-ci.com
        volumes:
            - hana-container-app-pdf:/var/www/html/hanaci-pdf
        networks:
            - hana-container-network
        depends_on:
            - hana-container-instance
    hana-container-postgres:
        image: postgres:16.1
        container_name: postgres-container
        restart: on-failure
        cpus: 1.0
        mem_limit: 256M
        mem_reservation: 128M
        ports:
            - '5432:5432'
        env_file:
            - module/.env
        environment:
            PGPASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - 'hana-container-postgres:/var/lib/postgresql/data'
        networks:
            - hana-container-network
        depends_on:
            - hana-container-instance
    hana-container-instance:
        image: nicklas373/hana-container-instance-sit:1.0
        container_name: instance-container
        cpus: 2.0
        mem_limit: 1024M
        mem_reservation: 512M
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./module/imagick/policy.xml:/etc/ImageMagick-6/policy.xml
            - ./module/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./module/nginx/sites-available/pdf-hanaci.conf:/etc/nginx/sites-available/pdf-hanaci.conf:ro
            - ./module/php/php.ini:/etc/php/8.2/cli/conf.d/99-hana.ini:ro
            - ./module/php/php.ini:/etc/php/8.2/fpm/conf.d/99-hana.ini:ro
            - hana-container-app-pdf:/var/www/html/hanaci-pdf
        networks:
            - hana-container-network
networks:
    hana-container-network:
        driver: bridge
volumes:
    hana-container-postgres:
        driver: local
    hana-container-app-pdf:
        driver: local
