name: HANA-CI PDF SIT Container

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Secrets
        run: |
          echo "Secrets: ${{ secrets.FTP_ROOT }}"
        env:
          DOCKER_SIT_ENVIRONMENT: ${{ secrets.docker_sit_env }}
          DB_USERNAME: ${{ secrets.docker_sit_env_FTP_ROOT }}
