name: HANA-CI PDF SIT Container

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          export DOCKER_COMPOSE_PATH=./docker-compose.yml
          docker buildx build \
            --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg ASPOSE_CLOUD_CLIENT_ID=${{ secrets.ASPOSE_CLOUD_CLIENT_ID }} \
            --build-arg ASPOSE_CLOUD_TOKEN=${{ secrets.ASPOSE_CLOUD_TOKEN }} \
            --build-arg ADOBE_CLIENT_ID=${{ secrets.ADOBE_CLIENT_ID }} \
            --build-arg FTP_USERNAME=${{ secrets.FTP_USERNAME }} \
            --build-arg FTP_USERPASS=${{ secrets.FTP_USERPASS }} \
            --build-arg FTP_SERVER=${{ secrets.FTP_SERVER }} \
            --build-arg FTP_ROOT=${{ secrets.FTP_ROOT }} \
            --build-arg ILOVEPDF_PUBLIC_KEY=${{ secrets.ILOVEPDF_PUBLIC_KEY }} \
            --build-arg ILOVEPDF_SECRET_KEY=${{ secrets.ILOVEPDF_SECRET_KEY }} \
            -t hanaci-app-pdf:latest nicklas373/hana-docker-sit-v2-hanaci-app-pdf:latest \
            -f Dockerfile/Dockerfile.hana-app-pdf.sit \
            .
          docker buildx build \
            --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg ASPOSE_CLOUD_CLIENT_ID=${{ secrets.ASPOSE_CLOUD_CLIENT_ID }} \
            --build-arg ASPOSE_CLOUD_TOKEN=${{ secrets.ASPOSE_CLOUD_TOKEN }} \
            --build-arg ADOBE_CLIENT_ID=${{ secrets.ADOBE_CLIENT_ID }} \
            --build-arg FTP_USERNAME=${{ secrets.FTP_USERNAME }} \
            --build-arg FTP_USERPASS=${{ secrets.FTP_USERPASS }} \
            --build-arg FTP_SERVER=${{ secrets.FTP_SERVER }} \
            --build-arg FTP_ROOT=${{ secrets.FTP_ROOT }} \
            --build-arg ILOVEPDF_PUBLIC_KEY=${{ secrets.ILOVEPDF_PUBLIC_KEY }} \
            --build-arg ILOVEPDF_SECRET_KEY=${{ secrets.ILOVEPDF_SECRET_KEY }} \
            -t hanaci-instance:latest nicklas373/hana-docker-sit-v2-hanaci-instance:latest \
            -f Dockerfile/Dockerfile.hana-instance.sit \
            .

      - name: Push Docker Image to Registry
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PAT }}
          docker push nicklas373/hanaci-app-pdf-sit:latest
          docker push nicklas373/hanaci-instance-sit:latest
