name: HANA-CI PDF SIT Container

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build HANA-CI PDF Docker Image
        run: |
          docker buildx create --use
          docker buildx build \
            --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg ASPOSE_CLOUD_CLIENT_ID=${{ secrets.ASPOSE_CLOUD_CLIENT_ID }} \
            --build-arg ASPOSE_CLOUD_TOKEN=${{ secrets.ASPOSE_CLOUD_TOKEN }} \
            --build-arg ADOBE_CLIENT_ID=${{ secrets.ADOBE_CLIENT_ID }} \
            --build-arg FTP_USERNAME=${{ secrets.FTP_USERNAME }} \
            --build-arg FTP_USERPASS=${{ secrets.FTP_USERPASS }} \
            --build-arg FTP_SERVER=${{ secrets.FTP_SERVER }} \
            --build-arg FTP_ROOT=${{ secrets.FTP_ROOT }} \
            --build-arg ILOVEPDF_PUBLIC_KEY=${{ secrets.ILOVEPDF_PUBLIC_KEY }} \
            --build-arg ILOVEPDF_SECRET_KEY=${{ secrets.ILOVEPDF_SECRET_KEY }} \
            -t hana-docker-sit-v2-hanaci-app-pdf:1.0 nicklas373/hana-docker-sit-v2-hanaci-app-pdf:1.0 \
            -f Dockerfile/Dockerfile.hana-app-pdf.sit \
            .
      - name: Build HANA-CI Instance Docker Image
        run: |
          docker buildx create --use
          docker buildx build \
            --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg ASPOSE_CLOUD_CLIENT_ID=${{ secrets.ASPOSE_CLOUD_CLIENT_ID }} \
            --build-arg ASPOSE_CLOUD_TOKEN=${{ secrets.ASPOSE_CLOUD_TOKEN }} \
            --build-arg ADOBE_CLIENT_ID=${{ secrets.ADOBE_CLIENT_ID }} \
            --build-arg FTP_USERNAME=${{ secrets.FTP_USERNAME }} \
            --build-arg FTP_USERPASS=${{ secrets.FTP_USERPASS }} \
            --build-arg FTP_SERVER=${{ secrets.FTP_SERVER }} \
            --build-arg FTP_ROOT=${{ secrets.FTP_ROOT }} \
            --build-arg ILOVEPDF_PUBLIC_KEY=${{ secrets.ILOVEPDF_PUBLIC_KEY }} \
            --build-arg ILOVEPDF_SECRET_KEY=${{ secrets.ILOVEPDF_SECRET_KEY }} \
            -t hana-docker-sit-v2-hanaci-instance:1.0 nicklas373/hana-docker-sit-v2-hanaci-instance:1.0 \
            -f Dockerfile/Dockerfile.hana-instance.sit \
            .
  verify:
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Verified Docker Image
        run: |
          docker images
          if docker images | grep -q nicklas373/hana-docker-sit-v2-hanaci-app-pdf:1.0; then
            echo "HANA-CI PDF App image container verified !."
          else
            echo "HANA-CI PDF App image container not found !, cancelling workflow."
            exit 1
          fi
          if docker images | grep -q nicklas373/hana-docker-sit-v2-hanaci-instance:1.0; then
            echo "HANA-CI PDF Instance image container verified !."
          else
            echo "HANA-CI PDF Instance image container not found !, cancelling workflow."
            exit 1
          fi

  push:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Deploy to SIT
        run: |
          echo ${{ secrets.DOCKER_PAT }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push nicklas373/hana-docker-sit-v2-hanaci-app-pdf:1.0
          docker push nicklas373/hana-docker-sit-v2-hanaci-instance:1.0
